/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AddTestDataView.java
 *
 * Created on Jun 4, 2009, 11:13:44 AM
 */

package com.ijunit.swing.view;

import javax.swing.JFrame;
import javax.swing.table.TableColumn;

import com.ijunit.swing.action.AddTestDataAction;
import com.ijunit.swing.component.ComboBoxRenderer;
import com.ijunit.swing.component.HistoryFactory;
import com.ijunit.swing.component.HistoryTextField;
import com.ijunit.swing.model.TestDataTblModel;

/**
 *
 * @author vcjain
 */
public class AddTestDataView extends javax.swing.JPanel {

	JFrame parentObject = null;
	TestDataTblModel model = null;
	AddTestDataAction action = null;
	
	
    /** Creates new form AddTestDataView */
    public AddTestDataView(TestDataTblModel model) {
    	this.model = model;
		action = new AddTestDataAction(this, model);
		initComponents();
		prepareComponents();

    }
    
    public void prepareComponents(){
    	dataTable.setModel(model);
    	dataTable.setAutoCreateColumnsFromModel(true);
    	TableColumn column = dataTable.getColumnModel().getColumn(0);
		column.setMaxWidth(35);
		column = dataTable.getColumnModel().getColumn(2);
		column.setCellEditor(new TableEditor(TableEditor.TESTDATA));
//		column.setCellRenderer(new TableRenderer(true, TableRenderer.TESTDATA));
		
    	getSaveBtn().addActionListener(action);
    	getExecuteBtn().addActionListener(action);
    	getCancelBtn().addActionListener(action);
    	getPreviewBtn().addActionListener(action);
    	getBrowseBtn().addActionListener(action);
    	getBrowseDataClassBtn().addActionListener(action);
    	getBrowseTestClassBtn().addActionListener(action);
    	getValueBtn.addActionListener(action);
    	
    	conditionNameCmb.setModel(new javax.swing.DefaultComboBoxModel());
    	conditionNameCmb.setEditable(true);
    	conditionNameCmb.addActionListener(action);
    	conditionNameCmb.setRenderer(new ComboBoxRenderer());
    	
    	getConditionDescTxtArea().setWrapStyleWord(true);
    	getTestClassTxtFld().addActionListener(action);
    	
    	disableBtn();
    	getSaveBtn().setEnabled(false);
    	
    	//Setting Mnemonics
    	getBrowseBtn().setMnemonic('B');
    	getBrowseDataClassBtn().setMnemonic('W');
    	getBrowseTestClassBtn().setMnemonic('R');
    	getExecuteBtn().setMnemonic('E');
    	getCancelBtn().setMnemonic('C');
    	getPreviewBtn().setMnemonic('P');
    	getValueBtn.setMnemonic('G');
    	
    	
    	//Only for Testing purpose
//    	getTestClassTxtFld().setText("com.mbi.ejb.patient.PatientServiceBean");
//    	getTestDataTxtFld().setText("com.mbi.common.data.patient.PatientData");
    }
    
    public void disableBtn(){
    	getValueBtn.setEnabled(false);
    	previewBtn.setEnabled(false);
    	executeBtn.setEnabled(false);
    }
    
    public void enableBtn(){
    	getValueBtn.setEnabled(true);
    	previewBtn.setEnabled(true);
    	executeBtn.setEnabled(true);
    }
    /**
	 * @return the parentObject
	 */
	public JFrame getParentObject() {
		return parentObject;
	}

	/**
	 * @param parentObject the parentObject to set
	 */
	public void setParentObject(JFrame parentObject) {
		this.parentObject = parentObject;
	}

	public AddTestDataView(JFrame parent, TestDataTblModel model) {
		this(model);
		this.parentObject = parent;
	}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

    	jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        sqlQueryTxtArea = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        dataFileTxtFld = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        browseBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        testClassTxtFld = new HistoryTextField(HistoryFactory.getInstance(HistoryFactory.TESTCLASS_HISTORY));
        browseTestClassBtn = new javax.swing.JButton();
        testDataTxtFld = new javax.swing.JTextField();
        sqltFileTxtFld = new javax.swing.JTextField();
        browseDataClassBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        conditionNameCmb = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        conditionDescTxtArea = new javax.swing.JTextArea();
        saveBtn = new javax.swing.JButton();
        executeBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        dataTable = new javax.swing.JTable();
        previewBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        getValueBtn = new javax.swing.JButton();

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setName("jPanel2"); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel2.setText("Add Test Data");
        jLabel2.setName("jLabel2"); // NOI18N

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setName("jPanel4"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        sqlQueryTxtArea.setColumns(20);
        sqlQueryTxtArea.setLineWrap(true);
        sqlQueryTxtArea.setRows(5);
        sqlQueryTxtArea.setName("sqlQueryTxtArea"); // NOI18N
        jScrollPane1.setViewportView(sqlQueryTxtArea);

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 12));
        jLabel3.setText("SQL Query");
        jLabel3.setName("jLabel3"); // NOI18N

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setName("jPanel5"); // NOI18N

        dataFileTxtFld.setName("dataFileTxtFld"); // NOI18N

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 12));
        jLabel1.setText("Data File");
        jLabel1.setName("jLabel1"); // NOI18N

        browseBtn.setFont(new java.awt.Font("Calibri", 0, 14));
        browseBtn.setText("Browse");
        browseBtn.setName("browseBtn"); // NOI18N
        browseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dataFileTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(browseBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(dataFileTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browseBtn))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel3)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setName("jPanel1"); // NOI18N

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 12));
        jLabel4.setText("Test Class");
        jLabel4.setName("jLabel4"); // NOI18N

        testClassTxtFld.setName("testClassTxtFld"); // NOI18N

        browseTestClassBtn.setFont(new java.awt.Font("Calibri", 0, 14));
        browseTestClassBtn.setText("Browse");
        browseTestClassBtn.setActionCommand("BrowseTestClass");
        browseTestClassBtn.setName("browseTestClassBtn"); // NOI18N
        browseTestClassBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseTestClassBtnActionPerformed(evt);
            }
        });

        testDataTxtFld.setName("testDataTxtFld"); // NOI18N

        sqltFileTxtFld.setName("sqltFileTxtFld"); // NOI18N

        browseDataClassBtn.setFont(new java.awt.Font("Calibri", 0, 14));
        browseDataClassBtn.setText("Browse");
        browseDataClassBtn.setActionCommand("BrowseDataClass");
        browseDataClassBtn.setName("browseDataClassBtn"); // NOI18N
        browseDataClassBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseDataClassBtnActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 12));
        jLabel6.setText("SQL Script File");
        jLabel6.setName("jLabel6"); // NOI18N

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 12));
        jLabel8.setText("Test Data Class");
        jLabel8.setName("jLabel8"); // NOI18N

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 12));
        jLabel7.setText("Condition Name");
        jLabel7.setName("jLabel7"); // NOI18N

        conditionNameCmb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        conditionNameCmb.setName("conditionNameCmb"); // NOI18N

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 12));
        jLabel9.setText("Description");
        jLabel9.setName("jLabel9"); // NOI18N

        jScrollPane3.setName("jScrollPane3"); // NOI18N

        conditionDescTxtArea.setColumns(20);
        conditionDescTxtArea.setRows(5);
        conditionDescTxtArea.setName("conditionDescTxtArea"); // NOI18N
        jScrollPane3.setViewportView(conditionDescTxtArea);

        saveBtn.setFont(new java.awt.Font("Calibri", 0, 14));
        saveBtn.setText("Save");
        saveBtn.setName("saveBtn"); // NOI18N
        saveBtn.setPreferredSize(new java.awt.Dimension(77, 25));
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        executeBtn.setFont(new java.awt.Font("Calibri", 0, 14));
        executeBtn.setText("Execute");
        executeBtn.setName("executeBtn"); // NOI18N
        executeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                executeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(browseTestClassBtn)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sqltFileTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(testClassTxtFld, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(testDataTxtFld, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                            .addComponent(browseDataClassBtn)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                            .addComponent(conditionNameCmb, 0, 345, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(executeBtn))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(testClassTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(browseTestClassBtn)
                    .addComponent(sqltFileTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(testDataTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(browseDataClassBtn)
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(conditionNameCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(executeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel9)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setName("jPanel3"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        dataTable.setAutoCreateColumnsFromModel(false);
        dataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        dataTable.setEditingColumn(2);
        dataTable.setName("dataTable"); // NOI18N
        jScrollPane2.setViewportView(dataTable);

        previewBtn.setFont(new java.awt.Font("Calibri", 0, 14));
        previewBtn.setText("Preview");
        previewBtn.setName("previewBtn"); // NOI18N
        previewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previewBtnActionPerformed(evt);
            }
        });

        cancelBtn.setFont(new java.awt.Font("Calibri", 0, 14));
        cancelBtn.setText("Cancel");
        cancelBtn.setName("cancelBtn"); // NOI18N
        cancelBtn.setPreferredSize(new java.awt.Dimension(77, 25));
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        getValueBtn.setFont(new java.awt.Font("Calibri", 0, 14));
        getValueBtn.setText("Get Value");
        getValueBtn.setName("getValueBtn"); // NOI18N
        getValueBtn.setPreferredSize(new java.awt.Dimension(77, 25));
        getValueBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getValueBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(91, Short.MAX_VALUE)
                        .addComponent(getValueBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(previewBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(previewBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(getValueBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(393, 393, 393))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, 0, 278, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1021, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
  }// </editor-fold>//GEN-END:initComponents

    private void browseDataClassBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseDataClassBtnActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_browseDataClassBtnActionPerformed

    private void browseTestClassBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseTestClassBtnActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_browseTestClassBtnActionPerformed

    private void browseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseBtnActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_browseBtnActionPerformed

    private void previewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previewBtnActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_previewBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_saveBtnActionPerformed

    private void executeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_executeBtnActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_executeBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void getValueBtnActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browseBtn;
    private javax.swing.JButton browseDataClassBtn;
    private javax.swing.JButton browseTestClassBtn;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JTextArea conditionDescTxtArea;
//    private javax.swing.JTextField conditionFileTxtFld;
    private javax.swing.JComboBox conditionNameCmb;
    private javax.swing.JTextField dataFileTxtFld;
    private javax.swing.JTable dataTable;
    private javax.swing.JButton executeBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton previewBtn;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTextArea sqlQueryTxtArea;
    private javax.swing.JTextField sqltFileTxtFld;
    private javax.swing.JTextField testClassTxtFld;
    private javax.swing.JTextField testDataTxtFld;
    private javax.swing.JButton getValueBtn;
    /**
	 * @return the getValueBtn
	 */
	public javax.swing.JButton getGetValueBtn() {
		return getValueBtn;
	}

	/**
	 * @param getValueBtn the getValueBtn to set
	 */
	public void setGetValueBtn(javax.swing.JButton getValueBtn) {
		this.getValueBtn = getValueBtn;
	}

	// End of variables declaration//GEN-END:variables
	/**
	 * @return the browseBtn
	 */
	public javax.swing.JButton getBrowseBtn() {
		return browseBtn;
	}

	/**
	 * @param browseBtn the browseBtn to set
	 */
	public void setBrowseBtn(javax.swing.JButton browseBtn) {
		this.browseBtn = browseBtn;
	}

	/**
	 * @return the browseDataClassBtn
	 */
	public javax.swing.JButton getBrowseDataClassBtn() {
		return browseDataClassBtn;
	}

	/**
	 * @param browseDataClassBtn the browseDataClassBtn to set
	 */
	public void setBrowseDataClassBtn(javax.swing.JButton browseDataClassBtn) {
		this.browseDataClassBtn = browseDataClassBtn;
	}

	/**
	 * @return the browseTestClassBtn
	 */
	public javax.swing.JButton getBrowseTestClassBtn() {
		return browseTestClassBtn;
	}

	/**
	 * @param browseTestClassBtn the browseTestClassBtn to set
	 */
	public void setBrowseTestClassBtn(javax.swing.JButton browseTestClassBtn) {
		this.browseTestClassBtn = browseTestClassBtn;
	}

	/**
	 * @return the cancelBtn
	 */
	public javax.swing.JButton getCancelBtn() {
		return cancelBtn;
	}

	/**
	 * @param cancelBtn the cancelBtn to set
	 */
	public void setCancelBtn(javax.swing.JButton cancelBtn) {
		this.cancelBtn = cancelBtn;
	}

	/**
	 * @return the conditionDescTxtArea
	 */
	public javax.swing.JTextArea getConditionDescTxtArea() {
		return conditionDescTxtArea;
	}

	/**
	 * @param conditionDescTxtArea the conditionDescTxtArea to set
	 */
	public void setConditionDescTxtArea(javax.swing.JTextArea conditionDescTxtArea) {
		this.conditionDescTxtArea = conditionDescTxtArea;
	}

	
	/**
	 * @return the conditionNameCmb
	 */
	public javax.swing.JComboBox getConditionNameCmb() {
		return conditionNameCmb;
	}

	/**
	 * @param conditionNameCmb the conditionNameCmb to set
	 */
	public void setConditionNameCmb(javax.swing.JComboBox conditionNameCmb) {
		this.conditionNameCmb = conditionNameCmb;
	}

	/**
	 * @return the dataFileTxtFld
	 */
	public javax.swing.JTextField getDataFileTxtFld() {
		return dataFileTxtFld;
	}

	/**
	 * @param dataFileTxtFld the dataFileTxtFld to set
	 */
	public void setDataFileTxtFld(javax.swing.JTextField dataFileTxtFld) {
		this.dataFileTxtFld = dataFileTxtFld;
	}

	/**
	 * @return the dataTable
	 */
	public javax.swing.JTable getDataTable() {
		return dataTable;
	}

	/**
	 * @param dataTable the dataTable to set
	 */
	public void setDataTable(javax.swing.JTable dataTable) {
		this.dataTable = dataTable;
	}

	/**
	 * @return the executeBtn
	 */
	public javax.swing.JButton getExecuteBtn() {
		return executeBtn;
	}

	/**
	 * @param executeBtn the executeBtn to set
	 */
	public void setExecuteBtn(javax.swing.JButton executeBtn) {
		this.executeBtn = executeBtn;
	}

	/**
	 * @return the previewBtn
	 */
	public javax.swing.JButton getPreviewBtn() {
		return previewBtn;
	}

	/**
	 * @param previewBtn the previewBtn to set
	 */
	public void setPreviewBtn(javax.swing.JButton previewBtn) {
		this.previewBtn = previewBtn;
	}

	/**
	 * @return the saveBtn
	 */
	public javax.swing.JButton getSaveBtn() {
		return saveBtn;
	}

	/**
	 * @param saveBtn the saveBtn to set
	 */
	public void setSaveBtn(javax.swing.JButton saveBtn) {
		this.saveBtn = saveBtn;
	}

	/**
	 * @return the sqlQueryTxtArea
	 */
	public javax.swing.JTextArea getSqlQueryTxtArea() {
		return sqlQueryTxtArea;
	}

	/**
	 * @param sqlQueryTxtArea the sqlQueryTxtArea to set
	 */
	public void setSqlQueryTxtArea(javax.swing.JTextArea sqlQueryTxtArea) {
		this.sqlQueryTxtArea = sqlQueryTxtArea;
	}

	/**
	 * @return the sqltFileTxtFld
	 */
	public javax.swing.JTextField getSqltFileTxtFld() {
		return sqltFileTxtFld;
	}

	/**
	 * @param sqltFileTxtFld the sqltFileTxtFld to set
	 */
	public void setSqltFileTxtFld(javax.swing.JTextField sqltFileTxtFld) {
		this.sqltFileTxtFld = sqltFileTxtFld;
	}

	/**
	 * @return the testClassTxtFld
	 */
	public javax.swing.JTextField getTestClassTxtFld() {
		return testClassTxtFld;
	}

	/**
	 * @param testClassTxtFld the testClassTxtFld to set
	 */
	public void setTestClassTxtFld(javax.swing.JTextField testClassTxtFld) {
		this.testClassTxtFld = testClassTxtFld;
	}

	/**
	 * @return the testDataTxtFld
	 */
	public javax.swing.JTextField getTestDataTxtFld() {
		return testDataTxtFld;
	}

	/**
	 * @param testDataTxtFld the testDataTxtFld to set
	 */
	public void setTestDataTxtFld(javax.swing.JTextField testDataTxtFld) {
		this.testDataTxtFld = testDataTxtFld;
	}

}
