/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ConfRootWizardView.java
 *
 * Created on Dec 9, 2009, 4:00:28 PM
 */

package com.ijunit.swing.view;

import javax.swing.BorderFactory;

import com.ijunit.resource.ResourceManager;

/**
 *
 * @author vcjain
 */
public class ConfRootWizardView extends javax.swing.JPanel {

    /** Creates new form ConfRootWizardView */
    public ConfRootWizardView() {
        initComponents();
        try{
        	browseBtn.setIcon(new javax.swing.ImageIcon(ResourceManager.getFile("browse.PNG").getAbsolutePath()));
        	classPathBtn.setIcon(new javax.swing.ImageIcon(ResourceManager.getFile("browse.PNG").getAbsolutePath()));
        	testClassPathBtn.setIcon(new javax.swing.ImageIcon(ResourceManager.getFile("browse.PNG").getAbsolutePath()));
        	logPathBtn.setIcon(new javax.swing.ImageIcon(ResourceManager.getFile("browse.PNG").getAbsolutePath()));
        }catch(Exception e){
        	browseBtn.setText("Browse");
        	classPathBtn.setText("Browse");
        	testClassPathBtn.setText("Browse");
        	logPathBtn.setText("Browse");
        }
    }

    /** Creates new form ConfRootWizardView */
    public ConfRootWizardView(String rootPath, String classPath, String logDir, String version) {
        initComponents();
        rootTextFld.setText(rootPath);
        classpathTextFld.setText(classPath);
        logTextFld.setText(logDir);
        versionTextField.setText(version);
        try{
        	browseBtn.setIcon(new javax.swing.ImageIcon(ResourceManager.getFile("browse.PNG").getAbsolutePath()));
        	classPathBtn.setIcon(new javax.swing.ImageIcon(ResourceManager.getFile("browse.PNG").getAbsolutePath()));
        	testClassPathBtn.setIcon(new javax.swing.ImageIcon(ResourceManager.getFile("browse.PNG").getAbsolutePath()));
        	logPathBtn.setIcon(new javax.swing.ImageIcon(ResourceManager.getFile("browse.PNG").getAbsolutePath()));
        }catch(Exception e){
        	browseBtn.setText("Browse");
        	classPathBtn.setText("Browse");
        	testClassPathBtn.setText("Browse");
        	logPathBtn.setText("Browse");
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        rootTextFld = new javax.swing.JTextField();
        browseBtn = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        classpathTextFld = new javax.swing.JTextField();
        classPathBtn = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        logTextFld = new javax.swing.JTextField();
        logPathBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        versionTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        testClasspathTextFld = new javax.swing.JTextField();
        testClassPathBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setName("jPanel1"); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Path"));
        jPanel2.setName("jPanel2"); // NOI18N

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 12));
        jLabel2.setText("Root Path");
        jLabel2.setName("jLabel2"); // NOI18N

        rootTextFld.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        rootTextFld.setName("rootTextFld"); // NOI18N
        rootTextFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rootTextFldActionPerformed(evt);
            }
        });

        browseBtn.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        browseBtn.setActionCommand("rootFolderBrowse");
        browseBtn.setName("browseBtn"); // NOI18N
        browseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseBtnAction(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel11.setText("(Specify path to Application classes.)");
        jLabel11.setName("jLabel11"); // NOI18N

        jLabel12.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel12.setText("Class Path");
        jLabel12.setName("jLabel12"); // NOI18N

        classpathTextFld.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        classpathTextFld.setToolTipText("like..c:\\eclispe..\\build\\classes");
        classpathTextFld.setName("classpathTextFld"); // NOI18N

        classPathBtn.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        classPathBtn.setActionCommand("classPathBrowse");
        classPathBtn.setName("classPathBtn"); // NOI18N
        classPathBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classPathBtnActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel14.setText("Log Path");
        jLabel14.setName("jLabel14"); // NOI18N

        logTextFld.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        logTextFld.setToolTipText("like..c:\\eclispe..\\build\\classes");
        logTextFld.setName("logTextFld"); // NOI18N

        logPathBtn.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        logPathBtn.setActionCommand("classPathBrowse");
        logPathBtn.setName("logPathBtn"); // NOI18N
        logPathBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logPathBtnActionPerformed(evt);
            }
        });

        jLabel4.setText("Version");
        jLabel4.setName("jLabel4"); // NOI18N

        versionTextField.setName("versionTextField"); // NOI18N

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel1.setText("(Specify Root folder to keep generated files.)");
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel13.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel13.setText("Class Path");
        jLabel13.setName("jLabel13"); // NOI18N

        jLabel15.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel15.setText("(Specify path to Test classes.)");
        jLabel15.setName("jLabel15"); // NOI18N

        testClasspathTextFld.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        testClasspathTextFld.setToolTipText("like..c:\\eclispe..\\build\\classes");
        testClasspathTextFld.setName("testClasspathTextFld"); // NOI18N

        testClassPathBtn.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        testClassPathBtn.setActionCommand("classPathBrowse");
        testClassPathBtn.setName("testClassPathBtn"); // NOI18N
        testClassPathBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testClassPathBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rootTextFld, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(browseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(classpathTextFld, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                                        .addComponent(classPathBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(testClassPathBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(72, 72, 72))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(testClasspathTextFld, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(versionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(logTextFld, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(logPathBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(rootTextFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(browseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(classpathTextFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(testClasspathTextFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(testClassPathBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(jLabel15))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(classPathBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(logTextFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logPathBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(versionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)))
        );

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 16));
        jLabel3.setText("Configuration Wizard");
        jLabel3.setName("jLabel3"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(7, 7, 7)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>
    
    
    private void rootTextFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rootTextFldActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_rootTextFldActionPerformed

    private void browseBtnAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseBtnAction
        // TODO add your handling code here:
}//GEN-LAST:event_browseBtnAction

    private void classPathBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classPathBtnActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_classPathBtnActionPerformed

    private void logPathBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logPathBtnActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_logPathBtnActionPerformed

    private void testClassPathBtnActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browseBtn;
    private javax.swing.JButton classPathBtn;
    private javax.swing.JTextField classpathTextFld;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton logPathBtn;
    private javax.swing.JTextField logTextFld;
    private javax.swing.JTextField rootTextFld;
    private javax.swing.JButton testClassPathBtn;
    private javax.swing.JTextField testClasspathTextFld;
    private javax.swing.JTextField versionTextField;
    // End of variables declaration//GEN-END:variables
	/**
	 * @return the classpathTextFld
	 */
	public javax.swing.JTextField getClasspathTextFld() {
		return classpathTextFld;
	}

	/**
	 * @param classpathTextFld the classpathTextFld to set
	 */
	public void setClasspathTextFld(javax.swing.JTextField classpathTextFld) {
		this.classpathTextFld = classpathTextFld;
	}

	/**
	 * @return the logTextFld
	 */
	public javax.swing.JTextField getLogTextFld() {
		return logTextFld;
	}

	/**
	 * @param logTextFld the logTextFld to set
	 */
	public void setLogTextFld(javax.swing.JTextField logTextFld) {
		this.logTextFld = logTextFld;
	}

	/**
	 * @return the rootTextFld
	 */
	public javax.swing.JTextField getRootTextFld() {
		return rootTextFld;
	}

	/**
	 * @param rootTextFld the rootTextFld to set
	 */
	public void setRootTextFld(javax.swing.JTextField rootTextFld) {
		this.rootTextFld = rootTextFld;
	}

	/**
	 * @return the versionTextField
	 */
	public javax.swing.JTextField getVersionTextField() {
		return versionTextField;
	}

	/**
	 * @param versionTextField the versionTextField to set
	 */
	public void setVersionTextField(javax.swing.JTextField versionTextField) {
		this.versionTextField = versionTextField;
	}

	/**
	 * @return the browseBtn
	 */
	public javax.swing.JButton getBrowseBtn() {
		return browseBtn;
	}

	/**
	 * @return the classPathBtn
	 */
	public javax.swing.JButton getClassPathBtn() {
		return classPathBtn;
	}

	/**
	 * @return the logPathBtn
	 */
	public javax.swing.JButton getLogPathBtn() {
		return logPathBtn;
	}

	/**
	 * @return the testClasspathTextFld
	 */
	public javax.swing.JTextField getTestClasspathTextFld() {
		return testClasspathTextFld;
	}

}
