/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ModifyTestDataView.java
 *
 * Created on Jun 4, 2009, 11:13:44 AM
 */

package com.ijunit.swing.view;

import javax.swing.JFrame;
import javax.swing.table.TableColumn;

import com.ijunit.swing.action.ModifyTestDataAction;
import com.ijunit.swing.component.ComboBoxRenderer;
import com.ijunit.swing.component.HistoryFactory;
import com.ijunit.swing.component.HistoryTextField;
import com.ijunit.swing.model.TestDataTblModel;

/**
 *
 * @author vcjain
 */
public class ModifyTestDataView extends javax.swing.JPanel {

	JFrame parentObject = null;
	TestDataTblModel model = null;
	ModifyTestDataAction action = null;
	
	
    /** Creates new form ModifyTestDataView */
    public ModifyTestDataView(TestDataTblModel model) {
    	this.model = model;
		action = new ModifyTestDataAction(this, model);
		initComponents();
		prepareComponents();

    }
    
    public void prepareComponents(){
    	dataTable.setModel(model);
    	dataTable.setAutoCreateColumnsFromModel(true);
    	TableColumn column = dataTable.getColumnModel().getColumn(0);
		column.setMaxWidth(35);
		column = dataTable.getColumnModel().getColumn(2);
		column.setCellEditor(new TableEditor(TableEditor.TESTDATA));
//		column.setCellRenderer(new TableRenderer(true, TableRenderer.TESTDATA));
		
    	getExecuteBtn().addActionListener(action);
    	getCancelBtn().addActionListener(action);
    	getPreviewBtn().addActionListener(action);
    	getBrowseTestClassBtn().addActionListener(action);
    	getValueBtn.addActionListener(action);
    	getSelectBtn().addActionListener(action);
    	
    	conditionNameCmb.setModel(new javax.swing.DefaultComboBoxModel());
    	conditionNameCmb.setRenderer(new ComboBoxRenderer());
    	testDataCmb.setModel(new javax.swing.DefaultComboBoxModel());
    	testDataCmb.setRenderer(new ComboBoxRenderer());
    	// Whilie modifying a TestData condition combo will be in Selection mode only.
    	conditionNameCmb.setEditable(false);
    	conditionNameCmb.addActionListener(action);
    	testDataCmb.addActionListener(action);
    	
    	getConditionDescTxtArea().setWrapStyleWord(true);
    	getTestClassTxtFld().addActionListener(action);
    	
    	disableBtn();
    	getSqltFileTxtFld().setEnabled(false);
    	
    	//Setting Mnemonics
    	getBrowseTestClassBtn().setMnemonic('B');
    	getSelectBtn().setMnemonic('S');
    	getCancelBtn().setMnemonic('C');
    	getValueBtn.setMnemonic('G');
    	getPreviewBtn().setMnemonic('P');
    	getExecuteBtn().setMnemonic('E');
    	
    	//Only for Testing purpose
//    	getTestClassTxtFld().setText("com.mbi.ejb.patient.PatientServiceBean");
//    	getTestDataTxtFld().setText("com.mbi.common.data.patient.PatientData");
    }
    
    public void disableBtn(){
    	getValueBtn.setEnabled(false);
    	previewBtn.setEnabled(false);
    	executeBtn.setEnabled(false);
    }
    
    public void enableBtn(){
    	getValueBtn.setEnabled(true);
    	previewBtn.setEnabled(true);
    	executeBtn.setEnabled(true);
    }
    /**
	 * @return the parentObject
	 */
	public JFrame getParentObject() {
		return parentObject;
	}

	/**
	 * @param parentObject the parentObject to set
	 */
	public void setParentObject(JFrame parentObject) {
		this.parentObject = parentObject;
	}

	public ModifyTestDataView(JFrame parent, TestDataTblModel model) {
		this(model);
		this.parentObject = parent;
	}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
private void initComponents() {

    	jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        sqlQueryTxtArea = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        dataTable = new javax.swing.JTable();
        previewBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        getValueBtn = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        testClassTxtFld = new HistoryTextField(HistoryFactory.getInstance(HistoryFactory.TESTCLASS_HISTORY));
        browseTestClassBtn = new javax.swing.JButton();
        sqltFileTxtFld = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        conditionNameCmb = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        conditionDescTxtArea = new javax.swing.JTextArea();
        executeBtn = new javax.swing.JButton();
        selectBtn = new javax.swing.JButton();
        testDataCmb = new javax.swing.JComboBox();

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setName("jPanel2"); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel2.setText("Modify Test Data");
        jLabel2.setName("jLabel2"); // NOI18N

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setName("jPanel4"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        sqlQueryTxtArea.setColumns(20);
        sqlQueryTxtArea.setFont(new java.awt.Font("Calibri", 0, 12));
        sqlQueryTxtArea.setLineWrap(true);
        sqlQueryTxtArea.setRows(5);
        sqlQueryTxtArea.setName("sqlQueryTxtArea"); // NOI18N
        jScrollPane1.setViewportView(sqlQueryTxtArea);

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 12));
        jLabel3.setText("SQL Query");
        jLabel3.setName("jLabel3"); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
                    .addComponent(jLabel3))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setName("jPanel3"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        dataTable.setAutoCreateColumnsFromModel(false);
        dataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        dataTable.setEditingColumn(2);
        dataTable.setName("dataTable"); // NOI18N
        jScrollPane2.setViewportView(dataTable);

        previewBtn.setFont(new java.awt.Font("Calibri", 0, 14));
        previewBtn.setText("Preview");
        previewBtn.setName("previewBtn"); // NOI18N
        previewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previewBtnActionPerformed(evt);
            }
        });

        cancelBtn.setFont(new java.awt.Font("Calibri", 0, 14));
        cancelBtn.setText("Cancel");
        cancelBtn.setName("cancelBtn"); // NOI18N
        cancelBtn.setPreferredSize(new java.awt.Dimension(77, 25));
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        getValueBtn.setFont(new java.awt.Font("Calibri", 0, 14));
        getValueBtn.setText("Get Value");
        getValueBtn.setName("getValueBtn"); // NOI18N
        getValueBtn.setPreferredSize(new java.awt.Dimension(77, 25));
        getValueBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getValueBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(99, Short.MAX_VALUE)
                        .addComponent(getValueBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(previewBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(previewBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(getValueBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setName("jPanel5"); // NOI18N
        jPanel5.setPreferredSize(new java.awt.Dimension(555, 284));

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 12));
        jLabel5.setText("Test Class");
        jLabel5.setName("jLabel5"); // NOI18N

        testClassTxtFld.setFont(new java.awt.Font("Calibri", 0, 12));
        testClassTxtFld.setName("testClassTxtFld1"); // NOI18N

        browseTestClassBtn.setFont(new java.awt.Font("Calibri", 0, 14));
        browseTestClassBtn.setText("Browse");
        browseTestClassBtn.setActionCommand("BrowseTestClass");
        browseTestClassBtn.setName("browseTestClassBtn1"); // NOI18N
        browseTestClassBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseTestClassBtnActionPerformed(evt);
            }
        });

        sqltFileTxtFld.setFont(new java.awt.Font("Calibri", 0, 12));
        sqltFileTxtFld.setName("sqltFileTxtFld1"); // NOI18N

        jLabel11.setFont(new java.awt.Font("Calibri", 0, 12));
        jLabel11.setText("SQL Script File");
        jLabel11.setName("jLabel11"); // NOI18N

        jLabel12.setFont(new java.awt.Font("Calibri", 0, 12));
        jLabel12.setText("Test Data Class");
        jLabel12.setName("jLabel12"); // NOI18N

        jLabel13.setFont(new java.awt.Font("Calibri", 0, 12));
        jLabel13.setText("Condition Name");
        jLabel13.setName("jLabel13"); // NOI18N

        conditionNameCmb.setFont(new java.awt.Font("Calibri", 0, 12));
        conditionNameCmb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        conditionNameCmb.setActionCommand("ConditionNameCmb");
        conditionNameCmb.setName("conditionNameCmb1"); // NOI18N

        jLabel14.setFont(new java.awt.Font("Calibri", 0, 12));
        jLabel14.setText("Description");
        jLabel14.setName("jLabel14"); // NOI18N

        jScrollPane4.setName("jScrollPane4"); // NOI18N

        conditionDescTxtArea.setColumns(20);
        conditionDescTxtArea.setFont(new java.awt.Font("Calibri", 0, 12));
        conditionDescTxtArea.setRows(5);
        conditionDescTxtArea.setName("conditionDescTxtArea1"); // NOI18N
        jScrollPane4.setViewportView(conditionDescTxtArea);

        executeBtn.setFont(new java.awt.Font("Calibri", 0, 14));
        executeBtn.setText("Execute");
        executeBtn.setName("executeBtn1"); // NOI18N
        executeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                executeBtnActionPerformed(evt);
            }
        });

        selectBtn.setFont(new java.awt.Font("Calibri", 0, 14));
        selectBtn.setText("Select");
        selectBtn.setName("selectBtn1"); // NOI18N
        selectBtn.setPreferredSize(new java.awt.Dimension(77, 25));
        selectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectBtnActionPerformed(evt);
            }
        });

        testDataCmb.setFont(new java.awt.Font("Calibri", 0, 12));
        testDataCmb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        testDataCmb.setActionCommand("TestDataCmb");
        testDataCmb.setName("testDataCmb"); // NOI18N
        testDataCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testDataCmbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(conditionNameCmb, 0, 333, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(testDataCmb, 0, 331, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(40, 40, 40)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(browseTestClassBtn)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel11)
                                        .addGap(18, 18, 18)
                                        .addComponent(sqltFileTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(testClassTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(11, 11, 11)))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selectBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(executeBtn))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(selectBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(executeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(testClassTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(browseTestClassBtn)
                            .addComponent(jLabel11)
                            .addComponent(sqltFileTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(testDataCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(conditionNameCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addComponent(jLabel14)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(393, 393, 393))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
 }// </editor-fold>//GEN-END:initComponents

    private void browseDataClassBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseDataClassBtnActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_browseDataClassBtnActionPerformed

    private void browseTestClassBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseTestClassBtnActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_browseTestClassBtnActionPerformed

    private void browseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseBtnActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_browseBtnActionPerformed

    private void previewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previewBtnActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_previewBtnActionPerformed

    
    private void executeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_executeBtnActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_executeBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void getValueBtnActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
}
    private void selectBtnActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
}
    private void testDataCmbActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browseTestClassBtn;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JTextArea conditionDescTxtArea;
    private javax.swing.JTextField conditionFileTxtFld;
    private javax.swing.JComboBox conditionNameCmb;
    private javax.swing.JTable dataTable;
    private javax.swing.JButton executeBtn;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton previewBtn;
    private javax.swing.JButton selectBtn;
    private javax.swing.JTextArea sqlQueryTxtArea;
    private javax.swing.JTextField sqltFileTxtFld;
    private javax.swing.JTextField testClassTxtFld;
    private javax.swing.JButton getValueBtn;
    private javax.swing.JComboBox testDataCmb;
    /**
	 * @return the getValueBtn
	 */
	public javax.swing.JButton getGetValueBtn() {
		return getValueBtn;
	}

	/**
	 * @param getValueBtn the getValueBtn to set
	 */
	public void setGetValueBtn(javax.swing.JButton getValueBtn) {
		this.getValueBtn = getValueBtn;
	}

	// End of variables declaration//GEN-END:variables
	
	/**
	 * @return the browseTestClassBtn
	 */
	public javax.swing.JButton getBrowseTestClassBtn() {
		return browseTestClassBtn;
	}

	/**
	 * @param browseTestClassBtn the browseTestClassBtn to set
	 */
	public void setBrowseTestClassBtn(javax.swing.JButton browseTestClassBtn) {
		this.browseTestClassBtn = browseTestClassBtn;
	}

	/**
	 * @return the cancelBtn
	 */
	public javax.swing.JButton getCancelBtn() {
		return cancelBtn;
	}

	/**
	 * @param cancelBtn the cancelBtn to set
	 */
	public void setCancelBtn(javax.swing.JButton cancelBtn) {
		this.cancelBtn = cancelBtn;
	}

	/**
	 * @return the conditionDescTxtArea
	 */
	public javax.swing.JTextArea getConditionDescTxtArea() {
		return conditionDescTxtArea;
	}

	/**
	 * @param conditionDescTxtArea the conditionDescTxtArea to set
	 */
	public void setConditionDescTxtArea(javax.swing.JTextArea conditionDescTxtArea) {
		this.conditionDescTxtArea = conditionDescTxtArea;
	}

	/**
	 * @return the conditionFileTxtFld
	 */
	public javax.swing.JTextField getConditionFileTxtFld() {
		return conditionFileTxtFld;
	}

	/**
	 * @param conditionFileTxtFld the conditionFileTxtFld to set
	 */
	public void setConditionFileTxtFld(javax.swing.JTextField conditionFileTxtFld) {
		this.conditionFileTxtFld = conditionFileTxtFld;
	}

	/**
	 * @return the conditionNameCmb
	 */
	public javax.swing.JComboBox getConditionNameCmb() {
		return conditionNameCmb;
	}

	/**
	 * @param conditionNameCmb the conditionNameCmb to set
	 */
	public void setConditionNameCmb(javax.swing.JComboBox conditionNameCmb) {
		this.conditionNameCmb = conditionNameCmb;
	}

	
	/**
	 * @return the selectBtn
	 */
	public javax.swing.JButton getSelectBtn() {
		return selectBtn;
	}

	/**
	 * @return the dataTable
	 */
	public javax.swing.JTable getDataTable() {
		return dataTable;
	}

	/**
	 * @param dataTable the dataTable to set
	 */
	public void setDataTable(javax.swing.JTable dataTable) {
		this.dataTable = dataTable;
	}

	/**
	 * @return the executeBtn
	 */
	public javax.swing.JButton getExecuteBtn() {
		return executeBtn;
	}

	/**
	 * @param executeBtn the executeBtn to set
	 */
	public void setExecuteBtn(javax.swing.JButton executeBtn) {
		this.executeBtn = executeBtn;
	}

	/**
	 * @return the previewBtn
	 */
	public javax.swing.JButton getPreviewBtn() {
		return previewBtn;
	}

	/**
	 * @param previewBtn the previewBtn to set
	 */
	public void setPreviewBtn(javax.swing.JButton previewBtn) {
		this.previewBtn = previewBtn;
	}

		
	/**
	 * @return the sqlQueryTxtArea
	 */
	public javax.swing.JTextArea getSqlQueryTxtArea() {
		return sqlQueryTxtArea;
	}

	/**
	 * @param sqlQueryTxtArea the sqlQueryTxtArea to set
	 */
	public void setSqlQueryTxtArea(javax.swing.JTextArea sqlQueryTxtArea) {
		this.sqlQueryTxtArea = sqlQueryTxtArea;
	}

	/**
	 * @return the sqltFileTxtFld
	 */
	public javax.swing.JTextField getSqltFileTxtFld() {
		return sqltFileTxtFld;
	}

	/**
	 * @param sqltFileTxtFld the sqltFileTxtFld to set
	 */
	public void setSqltFileTxtFld(javax.swing.JTextField sqltFileTxtFld) {
		this.sqltFileTxtFld = sqltFileTxtFld;
	}

	/**
	 * @return the testClassTxtFld
	 */
	public javax.swing.JTextField getTestClassTxtFld() {
		return testClassTxtFld;
	}

	/**
	 * @param testClassTxtFld the testClassTxtFld to set
	 */
	public void setTestClassTxtFld(javax.swing.JTextField testClassTxtFld) {
		this.testClassTxtFld = testClassTxtFld;
	}

	/**
	 * @return the testDataCmb
	 */
	public javax.swing.JComboBox getTestDataCmb() {
		return testDataCmb;
	}

	/**
	 * @param testDataCmb the testDataCmb to set
	 */
	public void setTestDataCmb(javax.swing.JComboBox testDataCmb) {
		this.testDataCmb = testDataCmb;
	}

	
}
