/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Start.java
 *
 * Created on Jun 3, 2009, 1:55:34 PM
 */

package com.ijunit.swing.view;

import java.io.File;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.UIManager;

import org.apache.log4j.Logger;

import com.ijunit.common.constant.IApplicationMsgCodes;
import com.ijunit.common.constant.IFileConstant;
import com.ijunit.common.exception.IJunitException;
import com.ijunit.common.utility.GTestClassLoader;
import com.ijunit.common.utility.ShutDownHook;
import com.ijunit.parser.ApplicationMessageParser;
import com.ijunit.resource.ResourceManager;
import com.ijunit.resource.ResourceManagerBase;
import com.ijunit.swing.model.DummyObjectDataTblModel;
import com.ijunit.swing.model.ObjectDataTableModel;
import com.ijunit.swing.model.TestDataTblModel;

/**
 *
 * @author vcjain
 */
public class Start extends javax.swing.JFrame {

	static{
		System.out.println("In the static block");
//		System.setProperty("log4j.debug", "true");
//		System.setProperty("ijunit.log.path","C:/JUnit/resource/log");
//		System.setProperty("log4j.configuration","resource/logging/ijunit-log4j.xml");
//		System.setProperty("logGTest.debug","true");
//		org.apache.log4j.Logger.getLogger(Start.class).debug("In logger ");
		
		System.out.println("Returning the static block");
	}
	
	Logger logger = Logger.getLogger(Start.class);
    /** Creates new form Start */
    public Start() {
    	super("Datum-Gen");
        initComponents();
        prepareComponent();
        showLogo();
        this.setSize(getMaximumSize());
        Runtime.getRuntime().addShutdownHook(new ShutDownHook());
    }

    public void prepareComponent(){
    	jMenu1.setMnemonic('N');
    	jMenu2.setMnemonic('E');
    	newDOMenuItem.setMnemonic('O');
    	newTestDataMenuItem.setMnemonic('T');
    	
    }
    
    public void showLogo(){
    	logger.debug("Entered in Start.showLogo()");
    	getContentPane().removeAll();
    	LogoPanel panel = new LogoPanel();
    	panel.setSize(getMaximumSize());
    	getContentPane().add(panel);
    	pack();
    	logger.debug("Exited from Start.showLogo()");
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        newDOMenuItem = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JSeparator();
        newTestDataMenuItem = new javax.swing.JMenuItem();
        dummyObjMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JSeparator();
        editDOMenuItem = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JSeparator();
        editTestDataMenuItem = new javax.swing.JMenuItem();
        searchMenu = new javax.swing.JMenu();
        searchTDMenuItem = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JSeparator();
        searchADMenuItem = new javax.swing.JMenuItem();
        toolMenu = new javax.swing.JMenu();
        dbConfMenuItem = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JSeparator();
        lFMenuItem = new javax.swing.JMenuItem();
        exitMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSeparator2.setName("jSeparator2"); // NOI18N

        jMenuBar1.setName("jMenuBar1"); // NOI18N

        jMenu1.setText("New");
        jMenu1.setName("jMenu1"); // NOI18N

        newDOMenuItem.setText("Object Data");
        newDOMenuItem.setName("newDOMenuItem"); // NOI18N
        newDOMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newDOMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(newDOMenuItem);

        jSeparator3.setName("jSeparator3"); // NOI18N
        jMenu1.add(jSeparator3);

        newTestDataMenuItem.setText("Test Data");
        newTestDataMenuItem.setName("newTestDataMenuItem"); // NOI18N
        newTestDataMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newTestDataMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(newTestDataMenuItem);

        dummyObjMenuItem.setText("Dummy Object");
        dummyObjMenuItem.setName("dummyObjMenuItem"); // NOI18N
        dummyObjMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dummyObjMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(dummyObjMenuItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenu2.setName("jMenu2"); // NOI18N

        jSeparator1.setName("jSeparator1"); // NOI18N
        jMenu2.add(jSeparator1);

        editDOMenuItem.setText("Data Object");
        editDOMenuItem.setName("editDOMenuItem"); // NOI18N
        editDOMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editDOMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(editDOMenuItem);

        jSeparator4.setName("jSeparator4"); // NOI18N
        jMenu2.add(jSeparator4);

        editTestDataMenuItem.setText("Test Data");
        editTestDataMenuItem.setName("editTestDataMenuItem"); // NOI18N
        editTestDataMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editTestDataMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(editTestDataMenuItem);

        jMenuBar1.add(jMenu2);

        searchMenu.setText("Search");
        searchMenu.setName("searchMenu"); // NOI18N
        searchMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchMenuActionPerformed(evt);
            }
        });

        searchTDMenuItem.setText("Test Data");
        searchTDMenuItem.setName("searchTDMenuItem"); // NOI18N
        searchTDMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTDMenuItemActionPerformed(evt);
            }
        });
        searchMenu.add(searchTDMenuItem);

        jSeparator5.setName("jSeparator5"); // NOI18N
        searchMenu.add(jSeparator5);

        searchADMenuItem.setText("App Data");
        searchADMenuItem.setName("searchADMenuItem"); // NOI18N
        searchADMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchADMenuItemActionPerformed(evt);
            }
        });
        searchMenu.add(searchADMenuItem);

        jMenuBar1.add(searchMenu);

        toolMenu.setText("Tools");
        toolMenu.setName("toolMenu"); // NOI18N
        toolMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toolMenuActionPerformed(evt);
            }
        });

        dbConfMenuItem.setText("DB Conf");
        dbConfMenuItem.setName("dbConfMenuItem"); // NOI18N
        dbConfMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dbConfMenuItemActionPerformed(evt);
            }
        });
        toolMenu.add(dbConfMenuItem);

        jSeparator6.setName("jSeparator6"); // NOI18N
        toolMenu.add(jSeparator6);

        lFMenuItem.setText("Look & Feel");
        lFMenuItem.setName("lFMenuItem"); // NOI18N
        lFMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lFMenuItemActionPerformed(evt);
            }
        });
        toolMenu.add(lFMenuItem);

        jMenuBar1.add(toolMenu);

        exitMenu.setText("Exit");
        exitMenu.setName("exitMenu"); // NOI18N
        exitMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMenuMouseClicked(evt);
            }
        });
        exitMenu.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                exitMenuMenuSelected(evt);
            }
        });
        exitMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuActionPerformed(evt);
            }
        });
        jMenuBar1.add(exitMenu);

        setJMenuBar(jMenuBar1);

//        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
//        getContentPane().setLayout(layout);
//        layout.setHorizontalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGap(0, 776, Short.MAX_VALUE)
//        );
//        layout.setVerticalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGap(0, 518, Short.MAX_VALUE)
//        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newDOMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newDataObjectAction
    	
		JPanel p = new AddObjectView(this,new ObjectDataTableModel());
		getContentPane().removeAll();
		p.setSize(getMaximumSize());
		getContentPane().add(p);
		pack();
    }//GEN-LAST:event_newDataObjectAction

    private void newTestDataMenuItemActionPerformed(java.awt.event.ActionEvent evt) {
    	JPanel p = new AddTestDataView(this,new TestDataTblModel());
		getContentPane().removeAll();
		p.setSize(getMaximumSize());
		getContentPane().add(p);
		pack();
    }

    private void editTestDataMenuItemActionPerformed(java.awt.event.ActionEvent evt) {
        logger.debug("Entered in Start.editTestDataMenuItemActionPerformed()");
        JPanel p = new ModifyTestDataView(this,new TestDataTblModel());
		getContentPane().removeAll();
		p.setSize(getMaximumSize());
		getContentPane().add(p);
		pack();
        logger.debug("Exited from Start.editTestDataMenuItemActionPerformed()");
    }

    private void editDOMenuItemActionPerformed(java.awt.event.ActionEvent evt) {
//        logger.debug("Entered in Start.editDOMenuItemActionPerformed()");
        JPanel p = new ModifyObjectView(this,new ObjectDataTableModel());
		getContentPane().removeAll();
		p.setSize(getMaximumSize());
		getContentPane().add(p);
		pack();
//        logger.debug("Exited from Start.searchMenuActionPerformed()");
    }

    private void searchMenuActionPerformed(java.awt.event.ActionEvent evt) {
//        logger.debug("Entered in Start.searchMenuActionPerformed()");
        
//        logger.debug("Exited from Start.searchADMenuItemActionPerformed()");
    }

    private void searchADMenuItemActionPerformed(java.awt.event.ActionEvent evt) {
//        logger.debug("Entered in Start.searchADMenuItemActionPerformed()");
        JPanel p = new SearchDataView(this);
		getContentPane().removeAll();
		p.setSize(getMaximumSize());
		getContentPane().add(p);
		pack();
//        logger.debug("Exited from Start.searchTDMenuItemActionPerformed()");
    }

    private void searchTDMenuItemActionPerformed(java.awt.event.ActionEvent evt) {
//        logger.debug("Entered in Start.searchTDMenuItemActionPerformed()");
        
//        logger.debug("Exited from Start.searchTDMenuItemActionPerformed()");
    }

    private void toolMenuActionPerformed(java.awt.event.ActionEvent evt) {
//        logger.debug("Entered in Start.toolMenuActionPerformed()");
        
//        logger.debug("Exited from Start.dbConfMenuItemActionPerformed()");
    }

    private void dbConfMenuItemActionPerformed(java.awt.event.ActionEvent evt) {
//        logger.debug("Entered in Start.dbConfMenuItemActionPerformed()");
        JPanel p = (JPanel)new ConfigurationView(this);
		getContentPane().removeAll();
		p.setSize(getMaximumSize());
		getContentPane().add(p);
		pack();
        
//        logger.debug("Exited from Start.lFMenuItemActionPerformed()");
}

    private void lFMenuItemActionPerformed(java.awt.event.ActionEvent evt) {
//        logger.debug("Entered in Start.lFMenuItemActionPerformed()");
        
//        logger.debug("Exited from Start.exitMenuActionPerformed()");
    }

    private void exitMenuActionPerformed(java.awt.event.ActionEvent evt) {
//    	logger.debug("Entered in Start.exitMenuActionPerformed()");
        System.exit(0);
    }
    
    private void exitMenuMenuSelected(javax.swing.event.MenuEvent evt) {
//        logger.debug("Entered in Start.exitMenuMenuSelected()");
        
//        logger.debug("Exited from Start.exitMenuMenuSelected()");
    }

    private void exitMenuMouseClicked(java.awt.event.MouseEvent evt) {
//        logger.debug("Entered in Start.exitMenuMouseClicked()");
        if (JOptionPane.showConfirmDialog(this, 
        		ApplicationMessageParser.getMessage(IApplicationMsgCodes.QUIT_MSG),	
        		"Datum-Gen", JOptionPane.YES_NO_OPTION)	== JOptionPane.YES_OPTION)
        {
        		System.exit(0);
        }
        
//        logger.debug("Exited from Start.exitMenuMouseClicked()");
    }
    
    private void dummyObjMenuItemActionPerformed(java.awt.event.ActionEvent evt) {
    	JPanel p = new AddDummyObjectView(this,new DummyObjectDataTblModel());
		getContentPane().removeAll();
		p.setSize(getMaximumSize());
		getContentPane().add(p);
		pack();
    }
    
    /**
    * @param args the command line arguments
     * @throws IJunitException 
     * @throws ClassNotFoundException 
    */
    public static void main(String args[]) throws IJunitException, Exception {
    	UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
    	
    	
    	WorkspaceDialog wkDiaglog = new WorkspaceDialog(null, true); 
		wkDiaglog.setVisible(true);
		
		if(ResourceManagerBase.resourceFileName == null || !(new File(ResourceManagerBase.resourceFileName).exists())){
			configureApplication(null);
		}
		
    	//Class.forName("com.ijunit.resource.ResourceManager");
    	System.setProperty("log4j.configuration", ResourceManager.getFile(IFileConstant.LOG4J_FILE).getAbsolutePath());
    	
    	final Start app = new Start();
    	GTestClassLoader.getInstance(Start.class.getClassLoader());
    	System.out.println("!!!!!!!!!!Welcome to Datum-Gen!!!!!!!!!!!");
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                app.setVisible(true);
            }
        });
        
		
    }

    public static void configureApplication(JFrame parent){
		ProgressDialog dialog = new ProgressDialog(parent,true);
		dialog.start(); 
		dialog.setLocation(320,300);
		dialog.setVisible(true);
		ConfigurationWizard wizard = new ConfigurationWizard(parent,true);
		wizard.setVisible(true);
	}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem dbConfMenuItem;
    private javax.swing.JMenuItem editDOMenuItem;
    private javax.swing.JMenuItem editTestDataMenuItem;
    private javax.swing.JMenuItem dummyObjMenuItem;
    private javax.swing.JMenu exitMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JMenuItem lFMenuItem;
    private javax.swing.JMenuItem newDOMenuItem;
    private javax.swing.JMenuItem newTestDataMenuItem;
    private javax.swing.JMenuItem searchADMenuItem;
    private javax.swing.JMenu searchMenu;
    private javax.swing.JMenuItem searchTDMenuItem;
    private javax.swing.JMenu toolMenu;
    // End of variables declaration//GEN-END:variables

}
