/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ConfRootWizard.java
 *
 * Created on Jul 28, 2009, 6:32:45 PM
 */

package com.ijunit.swing.view;

import java.awt.BorderLayout;
import java.awt.FlowLayout;

import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.UIManager;

import com.ijunit.swing.action.ConfigurationWizardAction;

/**
 *
 * @author vcjain
 */
public class ConfigurationWizard extends  javax.swing.JDialog {

	ConfigurationWizardAction action = null;
	ConfRootWizardView rootWizard = new ConfRootWizardView();
	ConfDBWizardView dbWizard = new ConfDBWizardView();
	ConfAppDBWizardView appDBWizard = new ConfAppDBWizardView();

    /** Creates new form ConfRootWizard */
    public ConfigurationWizard(java.awt.Frame parent, boolean modal) {
    	super(parent, modal);
        action = new ConfigurationWizardAction(this,rootWizard,dbWizard,appDBWizard);
        initComponents();
        prepareComponents();
    }

    
    public void prepareComponents() {
    	getFinishBtn().setEnabled(false);
    	getPreviousButton().setEnabled(false);
    	
    	nextBtn.addActionListener(action);
    	previousBtn.addActionListener(action);
    	cancelBtn.addActionListener(action);
    	finishBtn.addActionListener(action);
    	
    	rootWizard.getBrowseBtn().addActionListener(action);
    	rootWizard.getLogPathBtn().addActionListener(action);
    	rootWizard.getClassPathBtn().addActionListener(action);
    	
    	dbWizard.getTestConfBtn().addActionListener(action);
    	appDBWizard.getAppTestConfBtn().addActionListener(action);
    	
    	addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent e) {
                System.exit(0);
            }
        });
    	
    	setLocation(250,150);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        topPanel = new javax.swing.JPanel();
        buttonPanel = new javax.swing.JPanel();
        
        nextBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        previousBtn = new javax.swing.JButton();
        finishBtn = new javax.swing.JButton();
        
        buttonPanel.setLayout(new FlowLayout(FlowLayout.RIGHT));
        //buttonPanel.setBorder(BorderFactory.createEtchedBorder());
        buttonPanel.add(previousBtn);
        buttonPanel.add(nextBtn);
        buttonPanel.add(finishBtn);
        buttonPanel.add(cancelBtn);
        
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        nextBtn.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        nextBtn.setText("Next");
        nextBtn.setName("nextBtn"); // NOI18N
        nextBtn.setPreferredSize(new java.awt.Dimension(69, 25));
        
        finishBtn.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        finishBtn.setText("Finish");
        finishBtn.setName("finishBtn"); // NOI18N
        finishBtn.setPreferredSize(new java.awt.Dimension(69, 25));
        
        cancelBtn.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        cancelBtn.setText("Cancel");
        cancelBtn.setName("cancelBtn"); // NOI18N
        cancelBtn.setPreferredSize(new java.awt.Dimension(69, 25));
        
        previousBtn.setFont(new java.awt.Font("Calibri", 0, 12));
        previousBtn.setText("Previous");
        previousBtn.setName("previousButton"); // NOI18N
        previousBtn.setPreferredSize(new java.awt.Dimension(75, 25));
        
        tab = new JTabbedPane();
        tab.addTab("Root", rootWizard);
        tab.addTab("Datum-Gen Database", dbWizard);
        tab.addTab("Application Database", appDBWizard);
        
        JPanel p = new JPanel();
        p.add(tab);
        
        getContentPane().add(p);
        getContentPane().add(buttonPanel,BorderLayout.SOUTH);
        pack();
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) throws Exception{
    	UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ConfigurationWizard dialog = new ConfigurationWizard(null,true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton nextBtn;
    private javax.swing.JButton previousBtn;
    private javax.swing.JButton finishBtn;
    private javax.swing.JPanel topPanel;
    private javax.swing.JPanel buttonPanel;
    private JTabbedPane tab;
    // End of variables declaration//GEN-END:variables
	/**
	 * @return the cancelBtn
	 */
	public javax.swing.JButton getCancelBtn() {
		return cancelBtn;
	}

	/**
	 * @return the nextBtn
	 */
	public javax.swing.JButton getNextBtn() {
		return nextBtn;
	}

	/**
	 * @return the previousButton
	 */
	public javax.swing.JButton getPreviousButton() {
		return previousBtn;
	}

	/**
	 * @return the topPanel
	 */
	public javax.swing.JPanel getTopPanel() {
		return topPanel;
	}

	/**
	 * @return the finishBtn
	 */
	public javax.swing.JButton getFinishBtn() {
		return finishBtn;
	}

	/**
	 * @return the tab
	 */
	public JTabbedPane getTab() {
		return tab;
	}

}
