/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ConfAppDBWizardView.java
 *
 * Created on Jul 28, 2009, 7:33:29 PM
 */

package com.ijunit.swing.view;

import javax.swing.BorderFactory;

/**
 *
 * @author vcjain
 */
public class ConfAppDBWizardView extends javax.swing.JPanel {

	public final String DRIVER = "oracle.jdbc.driver.OracleDriver";
	public final String DATABASEURL = "jdbrc:oracle:thin";
	public final String PORT = "1521";
	
    /** Creates new form ConfAppDBWizardView */
    public ConfAppDBWizardView() {
        initComponents();
        prepareComponents();
    }
    
    public void prepareComponents() {
    	getAppDriverTextFld().setText(DRIVER);
    	getAppDBURLTextFld().setText(DATABASEURL);
    	getAppPortTextFld().setText(PORT);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        appDatabaseTextFld = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        appDriverTextFld = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        appDBURLTextFld = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        appHostTextFld = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        appPortTextFld = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        appUserNameTextFld = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        appPasswordTextFld = new javax.swing.JPasswordField();
        appTestConfBtn = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(479, 305));

        //jPanel1.setBorder(BorderFactory.createEtchedBorder());
        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(479, 305));

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel1.setText("Configuration Wizard");
        jLabel1.setName("jLabel1"); // NOI18N

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("i-emphsys DB Properties"));
        jPanel3.setName("jPanel3"); // NOI18N
        jPanel3.setPreferredSize(new java.awt.Dimension(484, 310));

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 12));
        jLabel3.setText("Database:");
        jLabel3.setName("jLabel3"); // NOI18N

        appDatabaseTextFld.setColumns(25);
        appDatabaseTextFld.setToolTipText("Database name");
        appDatabaseTextFld.setName("appDriverTextFld"); // NOI18N

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 12));
        jLabel4.setText("Driver:");
        jLabel4.setName("jLabel4"); // NOI18N

        appDriverTextFld.setColumns(50);
        appDriverTextFld.setToolTipText("like oracle.jdbc.OracleDriver");
        appDriverTextFld.setName("driverTextFld"); // NOI18N

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 12));
        jLabel5.setText("Database Url:");
        jLabel5.setName("jLabel5"); // NOI18N

        appDBURLTextFld.setColumns(50);
        appDBURLTextFld.setToolTipText("like jdbc:oracle:thin");
        appDBURLTextFld.setName("dbURLTextFld"); // NOI18N

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 12));
        jLabel6.setText("Host:");
        jLabel6.setName("jLabel6"); // NOI18N

        appHostTextFld.setColumns(20);
        appHostTextFld.setToolTipText("like 192.168.100.65");
        appHostTextFld.setName("appPortTextFld"); // NOI18N

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 12));
        jLabel7.setText("Port:");
        jLabel7.setName("jLabel7"); // NOI18N

        appPortTextFld.setColumns(6);
        appPortTextFld.setToolTipText("like..1521");
        appPortTextFld.setName("portTextFld"); // NOI18N

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 12));
        jLabel8.setText("Username:");
        jLabel8.setName("jLabel8"); // NOI18N

        appUserNameTextFld.setColumns(20);
        appUserNameTextFld.setToolTipText("like.. scott");
        appUserNameTextFld.setName("appPasswordTextFld"); // NOI18N

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 12));
        jLabel9.setText("Password:");
        jLabel9.setName("jLabel9"); // NOI18N

        appPasswordTextFld.setColumns(20);
        appPasswordTextFld.setToolTipText("");
        appPasswordTextFld.setName("passwordTextFld"); // NOI18N

        appTestConfBtn.setFont(new java.awt.Font("Calibri", 0, 12));
        appTestConfBtn.setText("Test");
        appTestConfBtn.setName("appTestConfBtn"); // NOI18N
        appTestConfBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appTestConfBtnAction(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(appDatabaseTextFld, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(appHostTextFld, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(appPasswordTextFld, 0, 0, Short.MAX_VALUE)
                            .addComponent(appUserNameTextFld, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57)
                        .addComponent(appTestConfBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(appPortTextFld, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(appDBURLTextFld, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(appDriverTextFld, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(appDatabaseTextFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(appDriverTextFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(appDBURLTextFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(appHostTextFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(appPortTextFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(appUserNameTextFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(appPasswordTextFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(appTestConfBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void appTestConfBtnAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appTestConfBtnAction
        // TODO add your handling code here:
}//GEN-LAST:event_appTestConfBtnAction


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField appDBURLTextFld;
    private javax.swing.JTextField appDatabaseTextFld;
    private javax.swing.JTextField appDriverTextFld;
    private javax.swing.JTextField appHostTextFld;
    private javax.swing.JPasswordField appPasswordTextFld;
    private javax.swing.JFormattedTextField appPortTextFld;
    private javax.swing.JButton appTestConfBtn;
    private javax.swing.JTextField appUserNameTextFld;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
	/**
	 * @return the appDatabaseTextFld
	 */
	public javax.swing.JTextField getAppDatabaseTextFld() {
		return appDatabaseTextFld;
	}

	/**
	 * @param appDatabaseTextFld the appDatabaseTextFld to set
	 */
	public void setAppDatabaseTextFld(javax.swing.JTextField appDatabaseTextFld) {
		this.appDatabaseTextFld = appDatabaseTextFld;
	}

	/**
	 * @return the appDBURLTextFld
	 */
	public javax.swing.JTextField getAppDBURLTextFld() {
		return appDBURLTextFld;
	}

	/**
	 * @param appDBURLTextFld the appDBURLTextFld to set
	 */
	public void setAppDBURLTextFld(javax.swing.JTextField appDBURLTextFld) {
		this.appDBURLTextFld = appDBURLTextFld;
	}

	/**
	 * @return the appDriverTextFld
	 */
	public javax.swing.JTextField getAppDriverTextFld() {
		return appDriverTextFld;
	}

	/**
	 * @param appDriverTextFld the appDriverTextFld to set
	 */
	public void setAppDriverTextFld(javax.swing.JTextField appDriverTextFld) {
		this.appDriverTextFld = appDriverTextFld;
	}

	/**
	 * @return the appHostTextFld
	 */
	public javax.swing.JTextField getAppHostTextFld() {
		return appHostTextFld;
	}

	/**
	 * @param appHostTextFld the appHostTextFld to set
	 */
	public void setAppHostTextFld(javax.swing.JTextField appHostTextFld) {
		this.appHostTextFld = appHostTextFld;
	}

	/**
	 * @return the appPasswordTextFld
	 */
	public javax.swing.JPasswordField getAppPasswordTextFld() {
		return appPasswordTextFld;
	}

	/**
	 * @param appPasswordTextFld the appPasswordTextFld to set
	 */
	public void setAppPasswordTextFld(javax.swing.JPasswordField appPasswordTextFld) {
		this.appPasswordTextFld = appPasswordTextFld;
	}

	/**
	 * @return the appPortTextFld
	 */
	public javax.swing.JFormattedTextField getAppPortTextFld() {
		return appPortTextFld;
	}

	/**
	 * @param appPortTextFld the appPortTextFld to set
	 */
	public void setAppPortTextFld(javax.swing.JFormattedTextField appPortTextFld) {
		this.appPortTextFld = appPortTextFld;
	}

	/**
	 * @return the appUserNameTextFld
	 */
	public javax.swing.JTextField getAppUserNameTextFld() {
		return appUserNameTextFld;
	}

	/**
	 * @param appUserNameTextFld the appUserNameTextFld to set
	 */
	public void setAppUserNameTextFld(javax.swing.JTextField appUserNameTextFld) {
		this.appUserNameTextFld = appUserNameTextFld;
	}

	/**
	 * @return the appTestConfBtn
	 */
	public javax.swing.JButton getAppTestConfBtn() {
		return appTestConfBtn;
	}

}
