/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GetValueDialog.java
 *
 * Created on Jun 12, 2009, 4:59:25 PM
 */

package com.ijunit.swing.view;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

import com.ijunit.swing.action.GetValueDialogAction;
import com.ijunit.swing.component.ComboBoxRenderer;
import com.ijunit.swing.model.SearchDataTblModel;

/**
 *
 * @author vcjain
 */
public class GetValueDialog extends javax.swing.JDialog {

	GetValueDialogAction action = null;
    /** Creates new form GetValueDialog */
    public GetValueDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        action = new GetValueDialogAction(this);
        prepareComponents();
    }
    
    /** Creates new form GetValueDialog */
    public GetValueDialog(java.awt.Frame parent, boolean modal, GetValueDialogAction action ) {
    	super(parent, modal);
    	this.action = action;
        initComponents();
        prepareComponents();
    }
    
    public void prepareComponents(){
    	dataTable.setModel(new DefaultTableModel());
    	//testClassTxtFld.addActionListener(action);
    	conditionNameCmb.addActionListener(action);
    	getValueBtn.addActionListener(action);
    	cancelBtn.addActionListener(action);
    	testDataCmb.addActionListener(action);
    	
    	testClassCmb.addActionListener(action);
    	    	
    	dataTable.setModel(new SearchDataTblModel());
    	TableColumn column = getDataTable().getColumnModel().getColumn(0);
		column.setMaxWidth(35);
    	
		conditionNameCmb.setModel(new javax.swing.DefaultComboBoxModel(new String[] {}));
		conditionNameCmb.setRenderer(new ComboBoxRenderer());
		testDataCmb.setModel(new javax.swing.DefaultComboBoxModel(new String[] {}));
		testDataCmb.setRenderer(new ComboBoxRenderer());
		testClassCmb.setModel(new javax.swing.DefaultComboBoxModel(new String[] {}));
		testClassCmb.setRenderer(new ComboBoxRenderer());
		this.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent e) {
            	GetValueDialog.this.setVisible(false);
            	GetValueDialog.this.dispose();
            }
        });
		//testClassTxtFld.setEnabled(false);
//    	Only for Testing purpose
//    	getTestClassTxtFld().setText("com.mbi.ejb.patient.PatientServiceBean");
//    	getTestDataTxtFld().setText("com.mbi.common.data.patient.PatientData");

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        getValueBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        dataTable = new javax.swing.JTable();
        cancelBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        conditionNameCmb = new javax.swing.JComboBox();
        testDataCmb = new javax.swing.JComboBox();
        testClassCmb = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setName("jPanel1"); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setName("jPanel2"); // NOI18N

        getValueBtn.setFont(new java.awt.Font("Calibri", 0, 12));
        getValueBtn.setText("Get Value");
        getValueBtn.setName("getValueBtn"); // NOI18N
        getValueBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getValueBtnActionPerformed(evt);
            }
        });

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        dataTable.setFont(new java.awt.Font("Calibri", 0, 12));
        dataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        dataTable.setName("dataTable"); // NOI18N
        jScrollPane2.setViewportView(dataTable);

        cancelBtn.setFont(new java.awt.Font("Calibri", 0, 12));
        cancelBtn.setText("Cancel");
        cancelBtn.setName("cancelBtn"); // NOI18N
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(328, Short.MAX_VALUE)
                .addComponent(cancelBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(getValueBtn)
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(11, 11, 11)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(getValueBtn)
                    .addComponent(cancelBtn)))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(9, 9, 9)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(30, Short.MAX_VALUE)))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setName("jPanel3"); // NOI18N

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel4.setText("Test Class");
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 12));
        jLabel8.setText("Test Data Class");
        jLabel8.setName("jLabel8"); // NOI18N

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 12));
        jLabel7.setText("Condition Name");
        jLabel7.setName("jLabel7"); // NOI18N

        conditionNameCmb.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        conditionNameCmb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        conditionNameCmb.setName("conditionNameCmb"); // NOI18N

        testDataCmb.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        testDataCmb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        testDataCmb.setName("testDataCmb"); // NOI18N
        testDataCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testDataCmbActionPerformed(evt);
            }
        });

        testClassCmb.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        testClassCmb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        testClassCmb.setName("testClassCmb"); // NOI18N
        testClassCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testClassCmbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(conditionNameCmb, 0, 170, Short.MAX_VALUE)
                                .addGap(217, 217, 217))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(testDataCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(testClassCmb, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(testClassCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(conditionNameCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(testDataCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void testClassCmbActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GetValueDialog dialog = new GetValueDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox conditionNameCmb;
    private javax.swing.JButton getValueBtn;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
//    private javax.swing.JTextField testClassTxtFld;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable dataTable;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JComboBox testDataCmb;
    private javax.swing.JComboBox testClassCmb;
	
	/**
	 * @return the testClassCmb
	 */
	public javax.swing.JComboBox getTestClassCmb() {
		return testClassCmb;
	}

	/**
	 * @return the conditionNameCmb
	 */
	public javax.swing.JComboBox getConditionNameCmb() {
		return conditionNameCmb;
	}

	/**
	 * @param conditionNameCmb the conditionNameCmb to set
	 */
	public void setConditionNameCmb(javax.swing.JComboBox conditionNameCmb) {
		this.conditionNameCmb = conditionNameCmb;
	}

	/**
	 * @return the dataTable
	 */
	public javax.swing.JTable getDataTable() {
		return dataTable;
	}

	/**
	 * @param dataTable the dataTable to set
	 */
	public void setDataTable(javax.swing.JTable dataTable) {
		this.dataTable = dataTable;
	}

	/**
	 * @return the getValueBtn
	 */
	public javax.swing.JButton getGetValueBtn() {
		return getValueBtn;
	}

	/**
	 * @param getValueBtn the getValueBtn to set
	 */
	public void setGetValueBtn(javax.swing.JButton getValueBtn) {
		this.getValueBtn = getValueBtn;
	}

//	/**
//	 * @return the testClassTxtFld
//	 */
//	public javax.swing.JTextField getTestClassTxtFld() {
//		return testClassTxtFld;
//	}
//
//	/**
//	 * @param testClassTxtFld the testClassTxtFld to set
//	 */
//	public void setTestClassTxtFld(javax.swing.JTextField testClassTxtFld) {
//		this.testClassTxtFld = testClassTxtFld;
//	}

	private void getValueBtnActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
	}

    private void testClassTxtFldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void browseTestClassBtnActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void browseDataClassBtnActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }
    
    private void testDataCmbActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }
    
    /**
	 * @return the cancelBtn
	 */
	public javax.swing.JButton getCancelBtn() {
		return cancelBtn;
	}

	/**
	 * @param cancelBtn the cancelBtn to set
	 */
	public void setCancelBtn(javax.swing.JButton cancelBtn) {
		this.cancelBtn = cancelBtn;
	}

	private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }
    
    public String getSelectedValue(){
    	return action.getSelectedValue();
    }

	public GetValueDialogAction getAction() {
		return action;
	}

	public void setAction(GetValueDialogAction action) {
		this.action = action;
	}

	/**
	 * @return the testDataCmb
	 */
	public javax.swing.JComboBox getTestDataCmb() {
		return testDataCmb;
	}

	/**
	 * @param testDataCmb the testDataCmb to set
	 */
	public void setTestDataCmb(javax.swing.JComboBox testDataCmb) {
		this.testDataCmb = testDataCmb;
	}

}
