/**
 * 
 */
package com.ijunit.common.constant;

/**
 * @author vcjain
 *
 */
public interface IApplicationMsgCodes 
{
	int CONNECTION_SUCCESS = 1;
	int SAVEXMLDATA_SUCCESS = 2;
	int TESTCLASS_BLANK = 3;
	int TESTDATACLASS_BLANK = 4;
	int CONDITION_BLANK = 5;
	int TESTDATA_TABLE_BLANK = 6;
	int SELECT_TESTDATA_FOR_INSER = 7;
	int DB_CONFIGURATION_BLANK = 8;
	int TESTDATA_INSERT_SUCCESS = 9;
	int SINGLE_SELECTION_MSG = 10;
	int SELECT_RECORD = 11;
	int EMPTY_VALUE = 12;
	int QUIT_MSG = 13;
	int SELECT_KEY_MSG = 14;
	int DATACOLUMN_REC_EXIST = 15;
	int NO_APPDATA_MSG = 16;
	int SELECT_TESTDATA_FOR_UPDATE = 17;
	int CONFIGURATION_CHANGE_MSG = 18;
	int SQLFILENAME_BLANK_MSG = 19;
	int NO_MATCHING_DATACLASS = 20;
	int SQLSAVED_SUCCESS_MSG = 21;
	int SQLUNSAVED_MSG = 22;
	int TESTDATA_UPDATE_SUCCESS = 23;
	int APP_RESTART_MSG = 24;
}
